### ISSUE TITLE
ndindex 1.7 apparently introduced some glitches in wheels for Win

### ISSUE THREAD

**Issue by FrancescAlted** [Quansight-Labs/ndindex#156]
Something happened in ndindex 1.7 that prevents [python-blosc2](https://github.com/Blosc/python-blosc2) package to use it straight from PyPI for Windows.  The ndindex dependency used to work well with [ndindex < 1.7](https://github.com/Blosc/python-blosc2/actions/runs/4656918527/jobs/8241003750), but recently we started to notice that [GHA was crashing on Windows](https://github.com/Blosc/python-blosc2/actions/runs/4849984057/jobs/8642482652).

The offending error happens when trying to import a wheel made out of ndindex 1.7:

```
ImportError: DLL load failed while importing ndindex: %1 is not a valid Win32 application.
```

Apparently, the making of the wheel goes well, but for some reason, it does not import on Win anymore.

**Comment by asmeurer** [comment]
I think the problem is that I forgot to build a py3-none wheel for 1.7. I need to make sure the release script does this in the future. The issue is that setup.py tries to cythonize the files when built https://quansight-labs.github.io/ndindex/#experimental-cythonization, but this is disabled for the pypi release. Apparently it doesn't work on Windows.

**Comment by asmeurer** [comment]
I uploaded a 1.7 wheel. If that doesn't fix the issue, it means you are building a wheel, and you should be able to fix the issue by setting `CYTHONIZE_NDINDEX=0`.

**Comment by FrancescAlted** [comment]
That [did the trick](https://github.com/Blosc/python-blosc2/actions/runs/4879908186/jobs/8706947210).  Thank you!
